version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: notes_db
    env_file:
      - .env.db.local
    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - notes_network

volumes:
  db_data:
    driver: local

networks:
  notes_network:
    driver: bridge